-- Tabela para armazenar conjuntos de templates
CREATE TABLE IF NOT EXISTS public.conjuntos_templates (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    nome TEXT NOT NULL,
    template1 TEXT NOT NULL,
    template2 TEXT,
    template3 TEXT,
    status TEXT DEFAULT 'ativo'
);

-- Tabela para armazenar campanhas
CREATE TABLE IF NOT EXISTS public.campanhas (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    nome TEXT NOT NULL,
    id_conjunto_template UUID REFERENCES public.conjuntos_templates(id),
    nome_conjunto_template TEXT,
    dia TEXT,
    periodo TEXT,
    status TEXT DEFAULT 'pendente',
    total_contatos INTEGER DEFAULT 0,
    contatos_enviados INTEGER DEFAULT 0,
    arquivo_nome TEXT,
    data_criacao TEXT
);

-- Tabela para armazenar conjuntos (conforme definição fornecida)
CREATE TABLE IF NOT EXISTS public."Conjuntos" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  constraint Conjuntos_pkey primary key (id)
) TABLESPACE pg_default;

-- Adicionar comentários às tabelas para documentação
COMMENT ON TABLE public.conjuntos_templates IS 'Armazena conjuntos de templates para mensagens de WhatsApp';
COMMENT ON TABLE public.campanhas IS 'Armazena campanhas de disparo de mensagens';
COMMENT ON TABLE public."Conjuntos" IS 'Tabela base para armazenar conjuntos';

-- Adicionar comentários às colunas
COMMENT ON COLUMN public.conjuntos_templates.id IS 'ID único do conjunto de templates';
COMMENT ON COLUMN public.conjuntos_templates.nome IS 'Nome do conjunto de templates';
COMMENT ON COLUMN public.conjuntos_templates.template1 IS 'Texto do primeiro template';
COMMENT ON COLUMN public.conjuntos_templates.template2 IS 'Texto do segundo template (opcional)';
COMMENT ON COLUMN public.conjuntos_templates.template3 IS 'Texto do terceiro template (opcional)';
COMMENT ON COLUMN public.conjuntos_templates.status IS 'Status do conjunto (ativo/inativo)';

COMMENT ON COLUMN public.campanhas.id IS 'ID único da campanha';
COMMENT ON COLUMN public.campanhas.nome IS 'Nome da campanha';
COMMENT ON COLUMN public.campanhas.id_conjunto_template IS 'ID do conjunto de templates usado';
COMMENT ON COLUMN public.campanhas.nome_conjunto_template IS 'Nome do conjunto de templates usado';
COMMENT ON COLUMN public.campanhas.dia IS 'Dia selecionado para a campanha (1 ou 2)';
COMMENT ON COLUMN public.campanhas.periodo IS 'Período selecionado (Manhã ou Tarde)';
COMMENT ON COLUMN public.campanhas.status IS 'Status da campanha (pendente, em_andamento, pausada, concluída)';
COMMENT ON COLUMN public.campanhas.total_contatos IS 'Total de contatos na campanha';
COMMENT ON COLUMN public.campanhas.contatos_enviados IS 'Número de contatos já processados';
COMMENT ON COLUMN public.campanhas.arquivo_nome IS 'Nome do arquivo original importado';
COMMENT ON COLUMN public.campanhas.data_criacao IS 'Data de criação da campanha em formato legível';
