// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Usar variáveis de ambiente para as credenciais do Supabase
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xqxmrkedkpdgfvtisnsf.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxeG1ya2Vka3BkZ2Z2dGlzbnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzYwODMsImV4cCI6MjA1NTgxMjA4M30.E4gxJupuA96mc2_V6g8Y166WcfOOA3oWKB906P5FBS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);